import json
import math
import os
import re

from groq import Groq

_client = None

MODEL = "qwen/qwen3.6-27b"

LLM_PROMPT = """You are a writing-forensics assistant. Read the passage below and \
assess how likely it is to have been generated by an AI language model, as opposed \
to written by a human.

Consider things like: generic phrasing, hedging patterns ("it is important to \
note", "on the other hand"), overly uniform structure, and a lack of a distinct \
personal voice.

Respond with ONLY a JSON object, no other text, in this exact shape:
{{"ai_likelihood": <float between 0.0 and 1.0>, "reason": "<one short sentence>"}}

A score of 1.0 means "certainly AI-generated." A score of 0.0 means "certainly \
human-written."

Passage:
\"\"\"
{text}
\"\"\"
"""


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def get_llm_score(text):
    """Returns a float in [0, 1]: the LLM signal's estimate that `text` is AI-generated."""
    client = _get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
        temperature=0,
        max_tokens=2048,
    )
    content = response.choices[0].message.content.strip()
    # Qwen3 models may prefix the answer with <think>...</think> reasoning tokens.
    # Strip them before parsing JSON.
    content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    # Some models wrap JSON in markdown code fences (```json ... ```). Strip those too.
    content = re.sub(r"```(?:json)?\s*(.*?)\s*```", r"\1", content, flags=re.DOTALL).strip()

    match = re.search(r"\{.*\}", content, re.DOTALL)
    if not match:
        raise ValueError(f"LLM signal did not return parseable JSON: {content!r}")

    parsed = json.loads(match.group(0))
    score = float(parsed["ai_likelihood"])
    return max(0.0, min(1.0, score))


def _split_sentences(text):
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s for s in sentences if s.strip()]


def _sentence_length_variance_score(sentences):
    """High score = sentence lengths are unusually uniform (an AI-like pattern)."""
    lengths = [len(s.split()) for s in sentences]
    if len(lengths) < 2:
        return 0.5  # not enough sentences to say anything meaningful
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    # Low variance -> uniform sentence lengths -> high AI-likelihood.
    return math.exp(-variance / 30)


def _type_token_ratio_score(text):
    """High score = narrow vocabulary diversity relative to length (an AI-like pattern)."""
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 5:
        return 0.5  # too short to measure vocabulary diversity meaningfully
    ttr = len(set(words)) / len(words)
    return max(0.0, min(1.0, 1 - ttr))


def _punctuation_density_score(text, sentences):
    """High score = heavy use of connective punctuation per sentence (an AI-like pattern)."""
    if not sentences:
        return 0.5
    connective_count = len(re.findall(r"[,;:]", text))
    density = connective_count / len(sentences)
    return max(0.0, min(1.0, density / 3))


def get_stylometric_score(text):
    """Returns a float in [0, 1]: the stylometric signal's estimate that `text` is AI-generated,
    based on sentence length uniformity, vocabulary diversity, and punctuation density."""
    sentences = _split_sentences(text)
    var_score = _sentence_length_variance_score(sentences)
    ttr_score = _type_token_ratio_score(text)
    punct_score = _punctuation_density_score(text, sentences)
    return (var_score + ttr_score + punct_score) / 3
